sudo: required

services:
  - docker

language: cpp

env:
  global:
    - COMPOSE_VERSION: 1.22.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose -v
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      name: "Base images"
      script:
        - docker-compose -f base/docker-compose.yaml build
        - docker images
        - docker push bitbots/bitbots-base:kinetic
        - docker push bitbots/bitbots-base:melodic
        - docker tag bitbots/bitbots-base:kinetic bitbots/bitbots-base:latest
        - docker push bitbots/bitbots-base:latest
    - stage: deploy
      name: "Domestic base image"
      script:
        - docker build -f domestic/melodic/Base.docker -t bitbots/bitbots-domestic:melodic-base domestic/melodic
        - docker images
        - docker push bitbots/bitbots-domestic:melodic-base
      name: "Industrial base image"
        - docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg UNAME=$kinetic_user -f industrial/kinetic/Dockerfile -t bitbots/bitbots-industrial:kinetic-base .
        - docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg UNAME=$melodic_user -f industrial/melodic/Dockerfile -t bitbots/bitbots-industrial:melodic-base .
        - docker images
        - docker push bitbots/bitbots-industrial:kinetic-base
        - docker push bitbots/bitbots-industrial:melodic-base


notifications:
  slack:
    secure: RUiplbRX8scnvplFZhBIvSJxPDs/qCcBiMmSZnocILQsHrZMCIhv0eNoAT6FWIkXpJbS4l56BFbSdZH25/qNl/cdNwbn/YCc4N4fketeYduLcWNpwOfbf41vjFIXEbzo6wboFjlIPJDZgQFbtMThoJ2Gx6J2nBLB719j4Skj5C58yx6/ScioXZZ1LIXEE1aeOwRnju+OqX/o0dvUNrnP+6XnMtuYSicml10JV5tj3r9IJQuSAD6Bv0l/2eMparJ5UboRMwtCy5GVLfetky6WARmESJP+bKhvYE1+FR3AdRmzA47rmE+c7fZzyybSRKeUlhWPUVatTLbWxpB4ivXxKfRWqe1RiYUIAQz8U2EhWgiuR47/1qYvQ4Lefq2pgZzbCTy4Z8rL4+CjuQqRrweAIS2AQuyWfcnv01BuJX7mmdR+jA0FYWSBxdTgrJLJ70y6ZiV6QGWYFW4x9mot3E6O+vh1LfI56ctpJfwHgIFwc0xN8rMhhkTNzEG911QAZPLsNp1+v18vXF5StHXc4sTM62IagVEifTjoVkJCTytKtqBIn+ZrAcxIBBZk8Mre9doT3ulCjRtzmGLEmGGHN429jY0ufjw1pdAml/a6FDKlKwp7/QZ49qeg23/OkkZCJ1MQ3kducjtO0qCV2DcCS7dS2b8q7ZJGH+gcWGc82XAsFgs=
