version: '2'
services:
  kinetic_base:
    build:
      dockerfile: kinetic/Dockerfile
      context: .
    image: bitbots/bitbots-base:kinetic
  melodic_base:
    build:
      dockerfile: melodic/Dockerfile
      context: .
    image: bitbots/bitbots-base:melodic
  noetic_base:
    build:
      dockerfile: noetic/Dockerfile
      context: .
    image: bitbots/bitbots-base:noetic
