---
name: cuda11.8.0-ubuntu22.04
on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - base-gpu-notebook/**
      - gpu-notebook/cuda11.8.0-ubuntu22.04/**
  schedule:
    - cron: "0 1 * * 0"

jobs:
  build-base-gpu-notebook:
    name: Build gpu-notebook image
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Install sphinx dependencies
      run: |
        sudo pip3 install --upgrade pip

    - name: Build image
      id: build_image
      run: |
        bash build_and_publish.sh --registry ghcr.io --publish "" --image "base-gpu-notebook" --cuda-version "cuda11.8.0-ubuntu22.04"

    - name: Docker image list
      run: docker images

  build-gpu-notebook:
    name: Build gpu-notebook image
    needs: build-base-gpu-notebook
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Install sphinx dependencies
      run: |
        sudo pip3 install --upgrade pip

    - name: Build image
      id: build_image
      run: |
        bash build_and_publish.sh --registry ghcr.io --publish "" --image "gpu-notebook" --cuda-version "cuda11.8.0-ubuntu22.04"

    - name: Docker image list
      run: docker images

  publish-base-gpu-notebook:
    name: Build and publish gpu-notebook
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      id: build_and_deploy_image
      run: |
        bash build_and_publish.sh --registry ghcr.io --publish "all" --image "base-gpu-notebook" --cuda-version "cuda11.8.0-ubuntu22.04"

    - name: Docker image list
      run: docker images

  publish-gpu-notebook:
    name: Build and publish gpu-notebook
    needs: publish-base-gpu-notebook
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      id: build_and_deploy_image
      run: |
        bash build_and_publish.sh --registry ghcr.io --publish "all" --image "gpu-notebook" --cuda-version "cuda11.8.0-ubuntu22.04"

    - name: Docker image list
      run: docker images

